src/game_dev_app/config/routes.rb
Rails.application.routes.draw do
  get 'project_dashboard/edit/:id', to: 'project_dashboard#edit', as: 'project_dashboard_edit'
  get 'project_dashboard/members/:id', to: 'project_dashboard#members', as: 'project_dashboard_members'
  get 'project_dashboard/requests/:id', to: 'project_dashboard#requests', as: 'project_dashboard_requests'
  get 'browse', to: 'browse#browse', as: 'browse'
  get 'my_dashboard/projects'
  get 'my_dashboard/offers'
  get 'my_dashboard/proposals'
  get 'my_dashboard/profile'
  devise_for :members, controllers: {registrations: 'members/registrations'}
  get 'projects/new'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :projects, except: [:index]
  resources :members, except: [:index]
  resources :offers, except: [:index]
  delete '/offers/:id', to: 'offers#destroy', as: 'offer_response'
  patch 'members', to: 'members/registrations#update', as: 'update_profile'
end

src/game_dev_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameDevApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Abel&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav>
      <% if member_signed_in? %>
        <%= link_to "Dashboard", my_dashboard_projects_path %> <%# should be dashboard_path %>
        <%= link_to "Browse", browse_path %>
        <%= link_to "Log out", destroy_member_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_member_session_path %>
        <%= link_to "Sign Up", new_member_registration_path %>
      <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>