src/game_dev_app/config/routes.rb
Rails.application.routes.draw do
  get 'project_dashboard/edit/:id', to: 'project_dashboard#edit', as: 'project_dashboard_edit'
  get 'project_dashboard/members/:id', to: 'project_dashboard#members', as: 'project_dashboard_members'
  get 'project_dashboard/requests/:id', to: 'project_dashboard#requests', as: 'project_dashboard_requests'
  get 'browse', to: 'browse#browse', as: 'browse'
  get 'my_dashboard/projects'
  get 'my_dashboard/offers'
  get 'my_dashboard/proposals'
  get 'my_dashboard/profile'
  devise_for :members, controllers: {registrations: 'members/registrations'}
  get 'projects/new'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :projects, except: [:index]
  resources :members, except: [:index]
  resources :offers, except: [:index]
  delete '/offers/:id', to: 'offers#destroy', as: 'offer_response'
  patch 'members', to: 'members/registrations#update', as: 'update_profile'
end

src/game_dev_app/app/controllers/project_dashboard_controller.rb
class ProjectDashboardController < ApplicationController
  before_action :authenticate_member!
  before_action :set_proj
  def edit
  end

  def members
  end

  def requests
    # outbound - offers where sender and project owner is current user
    @outbound_requests = []
    Offer.where(sender: current_member, response: nil).each do |pend|
      @outbound_requests << pend if pend.project_role.project == @project
    end
    # inbound - offers where receiver is current member and project is this project
    @inbound_requests = []
    Offer.where(receiver: current_member, response: nil).each do |pend|
      @inbound_requests << pend if pend.project_role.project == @project
    end
  end

  private
  def proj_params
    params.permit(:id)
  end
  def set_proj
    # get project using passed id
    @project = Project.find(proj_params[:id])
  end
end

src/game_dev_app/app/helpers/project_dashboard_helper.rb
module ProjectDashboardHelper
end

src/game_dev_app/app/views/project_dashboard/_project_dashboard_nav.html.erb
<nav>
    <%= link_to "Edit", project_dashboard_edit_path(id: @project.id) %>
    <%= link_to "Members", project_dashboard_members_path(id: @project.id) %>
    <%= link_to "Requests", project_dashboard_requests_path(id: @project.id) %>
</nav>

src/game_dev_app/app/views/project_dashboard/edit.html.erb
<%= render 'project_dashboard_nav' %>
<h1><%= @project.title %> - Edit Details</h1>
<%= form_with model: @project, local: true do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.label :duration %>
        <%= f.text_field :duration %>
    </div>
    <div>
        <%= f.label :budget %>
        <%= f.text_field :budget %>
    </div>
    <div>
        <%= f.label :images %>
        <%= f.file_field :images %>
    </div>
    <h2>Add Role</h2>
    <%= f.nested_fields_for :project_roles do |role_form| %>
        <div>
            <%= role_form.label :expertise %>
            <%= role_form.select :expertise, options_from_collection_for_select(Expertise.all, "id", "title"), name: 'project_expertise' %>    
        </div>
        <div>
            <%= role_form.label :description %>
            <%= role_form.text_area :description  %>
        </div>
        <%= role_form.remove_nested_fields_link do %>
            <span>Remove role</span>
        <% end %>
    <% end %>
    <%= f.add_nested_fields_link :project_roles do %>
        <span>Add another role</span>
    <% end %>
    <br /><br />
    <%= f.submit "Post Project" %>
<% end %>

src/game_dev_app/app/views/project_dashboard/members.html.erb
<%= render 'project_dashboard_nav' %>
<h1><%= @project.title %> - Members</h1>
<%# get roles of this project %>
<% @project.project_roles.each do |role| %>
    <%# for some reason role.member didn't work here %>
    <%# find the member filling this role using id %>
    <% if role.member_id then %>
        <h2><%= Member.find(role.member_id).full_name %> - <%= role.expertise.title %></h2>
    <% end %>
<% end %>

src/game_dev_app/app/views/project_dashboard/requests.html.erb
<%= render 'project_dashboard_nav' %>
<h1>Project Dashboard - Requests</h1>
<h2>Inbound</h2>
<% @inbound_requests.each do |req| %>
    <p>From: <%= req.sender.full_name %></p>
    <p>Role: <%= req.project_role.expertise.title %></p>
    <p>Description: <%= req.description %></p>
    <%= link_to "Accept", offer_response_path(id: req.id, offer: {response: true}), method: :delete %>
    <%= link_to "Decline", offer_response_path(id: req.id, offer: {response: false}), method: :delete %>
<% end %>
<h2>Outbound</h2>
<% @outbound_requests.each do |req| %>
    <p>To: <%= req.receiver.full_name %></p>
    <p>Role: <%= req.project_role.expertise.title %></p>
    <p>Description: <%= req.description %></p>
<% end %>