src/game_dev_app/config/routes.rb
Rails.application.routes.draw do
  get 'project_dashboard/edit/:id', to: 'project_dashboard#edit', as: 'project_dashboard_edit'
  get 'project_dashboard/members/:id', to: 'project_dashboard#members', as: 'project_dashboard_members'
  get 'project_dashboard/requests/:id', to: 'project_dashboard#requests', as: 'project_dashboard_requests'
  get 'browse', to: 'browse#browse', as: 'browse'
  get 'my_dashboard/projects'
  get 'my_dashboard/offers'
  get 'my_dashboard/proposals'
  get 'my_dashboard/profile'
  devise_for :members, controllers: {registrations: 'members/registrations'}
  get 'projects/new'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :projects, except: [:index]
  resources :members, except: [:index]
  resources :offers, except: [:index]
  delete '/offers/:id', to: 'offers#destroy', as: 'offer_response'
  patch 'members', to: 'members/registrations#update', as: 'update_profile'
end

src/game_dev_app/app/controllers/my_dashboard_controller.rb
class MyDashboardController < ApplicationController
  before_action :authenticate_member!
  def projects

    # get all projects that this member owns
    @owned_projects = Project.where(owner: current_member)
    
    # get all roles that this member has
    @roles = current_member.project_roles

  end

  def offers
    # when someone is asking you to work on their project
    # get offers where receiver is current member and 
    # attached project role owner is not current member
    @offers = []
    Offer.where(receiver: current_member).each do |offer|
      @offers << offer if offer.project_role.project.owner != current_member
    end
  end

  def proposals
    # you ask someone if you can work on their project
    # get offers where sender is current member and 
    # attached project role owner is not current member
    @proposals = []
    Offer.where(sender: current_member).each do |pend|
      @proposals << pend if pend.project_role.project.owner != current_member
    end
  end

  def profile
    if not current_member.profile_complete? then
      # build member expertises so they show up in 
      # nested forms
      current_member.member_expertises.build
    end
  end

end

src/game_dev_app/app/helpers/my_dashboard_helper.rb
module MyDashboardHelper
end

src/game_dev_app/app/views/my_dashboard/_my_dashboard_nav.html.erb
<nav>
    <%= link_to "Projects", my_dashboard_projects_path %>
    <%= link_to "Offers", my_dashboard_offers_path %>
    <%= link_to "Proposals", my_dashboard_proposals_path %>
    <%= link_to "Profile", my_dashboard_profile_path %>
</nav>

src/game_dev_app/app/views/my_dashboard/offers.html.erb
<%= render 'my_dashboard_nav' %>
<h1>My Dashboard - Offers</h1>
<% @offers.each do |offer| %>
    <h2><%= offer.project_role.project.title %></h2>
    <p>From: <%= offer.sender.full_name %></p>
    <p>Position: <%= offer.project_role.expertise.title %></p>
    <%= link_to "Accept", offer_response_path(id: offer.id, offer: {response: true}), method: :delete %>
    <%= link_to "Decline", offer_response_path(id: offer.id, offer: {response: false}), method: :delete %>
<% end %>

src/game_dev_app/app/views/my_dashboard/profile.html.erb
<%= render 'my_dashboard_nav' %>
<%# either show profile or button to create one %>
<% if not current_member.profile_complete? then %>
    
    <h1>Complete Your Profile</h1>
    <%= form_with model: current_member, url: update_profile_path(current_member), local: true do |f| %>
        <div>
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name %><br />
        </div>
        <div>
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name %><br />
        </div>
        <div>
            <%= f.label :about_me %><br />
            <%= f.text_area :about_me %><br />
        </div>
        <h2>Areas of Expertise</h2>
        <%= f.nested_fields_for :member_expertises do |me| %>
            <div>
                <%= me.label :expertise %>
                <%= me.select :expertise, options_from_collection_for_select(Expertise.all, "id", "title"), name: 'project_expertise' %>    
            </div>
            <div>
                <%= me.label :description %>
                <%= me.text_area :description  %>
            </div>
            <%= me.remove_nested_fields_link do %>
                <span>Remove role</span>
            <% end %>
        <% end %>
        <%= f.add_nested_fields_link :member_expertises do %>
            <span>Add another expertise</span><br />
        <% end %>
        <%= f.submit "Complete Profile" %>
    <% end %>
<% else %>

    <h1>My Dashboard - Profile</h1>
    <h2><%= current_member.full_name %></h2>
    <% current_member.expertises.each do |exp| %>
        <p><%= exp.title %></p>
    <% end %>
    <h2>About Me</h2>
    <p><%= current_member.about_me %></p>
    <h2>Portfolio</h2>
    <% current_member.member_expertises.each do |me| %>
        <h3><%= me.expertise.title %></h3>
        <p><%= me.description %></p>
    <% end %>

<% end %>

src/game_dev_app/app/views/my_dashboard/projects.html.erb
<%= render 'my_dashboard_nav' %>
<h1>My Dashboard - Projects</h1>
<%= link_to 'New Project', projects_new_path %>
<% @owned_projects.each do |p| %>
    <h2><%= p.title %> - Owner</h2>
    <p><%= p.description %></p>
    <%= link_to 'Manage', project_dashboard_edit_path(id: p.id) %>
    <%= link_to 'View', project_path(id: p.id) %>
<% end %>
<% @roles.each do |role| %>
    <h2><%= role.role_title %></h2>
    <p><%= role.project.description %></p>
    <%= link_to 'View', project_path(id: role.project.id) %>
<% end %>

src/game_dev_app/app/views/my_dashboard/proposals.html.erb
<%= render 'my_dashboard_nav' %>
<h1>My Dashboard - Proposals</h1>
<% @proposals.each do |prop| %>
    <div class="offer">
        <h3><%= prop.project_role.project.title %></h3>
        <p>Project Owner: <%= prop.receiver.full_name %></p>
        <p>Applying for: <%= prop.project_role.expertise.title %></p>
        <p>Message: <%= prop.description %></p>
    </div>
<% end %>