src/game_dev_app/config/routes.rb
Rails.application.routes.draw do
  get 'project_dashboard/edit/:id', to: 'project_dashboard#edit', as: 'project_dashboard_edit'
  get 'project_dashboard/members/:id', to: 'project_dashboard#members', as: 'project_dashboard_members'
  get 'project_dashboard/requests/:id', to: 'project_dashboard#requests', as: 'project_dashboard_requests'
  get 'browse', to: 'browse#browse', as: 'browse'
  get 'my_dashboard/projects'
  get 'my_dashboard/offers'
  get 'my_dashboard/proposals'
  get 'my_dashboard/profile'
  devise_for :members, controllers: {registrations: 'members/registrations'}
  get 'projects/new'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :projects, except: [:index]
  resources :members, except: [:index]
  resources :offers, except: [:index]
  delete '/offers/:id', to: 'offers#destroy', as: 'offer_response'
  patch 'members', to: 'members/registrations#update', as: 'update_profile'
end

src/game_dev_app/app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  before_action :authenticate_member!
  def browse
    @params = browse_params
    @results = []
    if @params[:group] == "Work" then
      # return project roles that match the expertise
      # search criteria
      ProjectRole.where(expertise_id: @params[:project_expertise]).each do |role|
        @results << role if not role.member_id
      end
    else
      # return members with areas of expertise that match the expertise
      # search criteria
      @results = MemberExpertise.where(expertise_id: @params[:project_expertise])
    end
  end
  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def browse_params
      params.permit(:group, :project_expertise)
    end
end

src/game_dev_app/app/helpers/browse_helper.rb
module BrowseHelper
end

src/game_dev_app/app/views/browse/browse.html.erb
<h1>Browse</h1>

<!-- filter -->
<%= form_with(url: browse_path, method: "get", local: true) do %>
  <%= label_tag(:group, "I want to:") %>
  <%= select_tag(:group, options_for_select(["Hire", "Work"])) %>
  <%= label_tag(:expertise, "a:") %>
  <%= select_tag :expertise, options_from_collection_for_select(Expertise.all, "id", "title"), name: 'project_expertise' %>
  <%= submit_tag("Search") %>
<% end %>

<!-- list results -->
<% if @params[:group] == "Work" then %>
    <!-- display vacant roles matching search criteria -->
    <% @results.each do |role| %>
        <h2><%= link_to role.project.title, project_path(id: role.project.id) %></h2>
        <h3><%= role.expertise.title %></h3>
        <p><%= role.description %></p>
    <% end %>
<% else %>
    <!-- display creatives whose expertise matches search criteria -->
    <% @results.each do |member_expertise| %>
        <h2><%= link_to member_expertise.member.full_name, member_path(id: member_expertise.member_id) %></h2>
        <h3><%= member_expertise.expertise.title %></h3>
        <p><%= member_expertise.member.about_me %></p>

    <% end %>
<% end %>